apiVersion: apps/v1
kind: Deployment
metadata:
  name: fixssx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fixssx
  template:
    metadata:
      labels:
        app: fixssx
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: fixssx
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "7b110f69-07e3-42a3-961d-72cd539ec48b"
        - name: Vless_Path
          value: "/vl55x1"
        - name: Vmess_UUID
          value: "7b110f69-07e3-42a3-961d-72cd539ec48b"
        - name: Vmess_Path
          value: "/vm66x2"
        - name: Share_Path
          value: "/v2link"
